In [71]:
import pandas as pd
df=pd.read_csv(r"C:\Users\nk424\OneDrive\Scans\Desktop\training\Sample_Data\house price prediction.csv")
df.head()

bath  balcony  ...  location_Mahadevpura  location_Tumkur Road
0   3.0      2.0  ...                     0                     0
1   3.0      3.0  ...                     0                     0
2   3.0      2.0  ...                     0                     0
3   2.0      2.0  ...                     0                     0
4   2.0      2.0  ...                     0                     0

[5 rows x 108 columns]

In [72]:
df.shape

(7120, 108)

In [73]:
# price is our target value which conatain contineous values so we will apply linearregression
df.isnull().sum()

bath                           0
balcony                        0
price                          0
total_sqft_int                 0
bhk                            0
                              ..
location_Hosur Road            0
location_Horamavu Banaswadi    0
location_Domlur                0
location_Mahadevpura           0
location_Tumkur Road           0
Length: 108, dtype: int64

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7120 entries, 0 to 7119
Columns: 108 entries, bath to location_Tumkur Road
dtypes: float64(5), int64(103)
memory usage: 5.9 MB


In [75]:
x=df.drop('price',axis=1)
y=df['price']

In [76]:
x.shape

(7120, 107)

In [77]:
y.shape

(7120,)

In [78]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=500)


In [79]:
print("shape of x_train",x_train.shape)
print("shape of x_test",x_test.shape)



shape of x_train (5696, 107)
shape of x_test (1424, 107)


In [80]:
print("shape of y_train",y_train.shape)
print("shape of y_test",y_test.shape)

shape of y_train (5696,)
shape of y_test (1424,)


In [81]:
from sklearn.preprocessing import StandardScaler
std=StandardScaler()
std.fit(x_train)
x_train=std.transform(x_train)
x_test=std.transform(x_test)

In [82]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [83]:
x_test[0,:]

array([ 0.68477589,  0.55450841,  0.51886404,  0.62099968,  2.03886793,
        0.58464853, -0.47983078, -0.25703648, -2.01571603, -0.1862679 ,
       -0.15639831, -0.15222439, -0.12741862, -0.13570511, -0.13162265,
       -0.12381344, -0.12526719, -0.12010681, -0.12160223, -0.1107353 ,
       -0.11314714, -0.1107353 , -0.10909925, -0.11472827, -0.0941054 ,
       -0.09315135, -0.09218776, -0.08823182, -0.08721571, -0.08085949,
       -0.08195215, -0.0830308 , -0.08195215, -0.0830308 , -0.07749158,
       -0.0751646 , -0.0751646 , -0.07749158, -0.07153563, -0.07975227,
       -0.07633675, -0.07276497, -0.0739743 , -0.07276497, -0.07028523,
       -0.07749158, -0.0751646 , -0.07028523, -0.07276497, -0.07276497,
       -0.06901264, -0.06639573, -0.06504853, -0.06901264, -0.07153563,
       -0.06639573, -0.06639573, -0.06901264, -0.06901264, -0.06367332,
       -0.06226825, -0.06226825, -0.06901264, -0.06367332, -0.06367332,
       -0.05935999, -0.05785186, -0.06083125, -0.06226825, -0.06

In [84]:
lr.predict([x_test[0,:]])

array([283.03932643])

In [85]:
y_test

1680    224.00
2651    125.00
1826     42.00
2788    119.00
741      65.00
         ...  
359      52.00
5806    235.00
3384     80.04
5228     55.47
4366     91.00
Name: price, Length: 1424, dtype: float64

In [86]:
lr.predict([x_test[1,:]])

array([126.76371717])

In [87]:
lr.predict([x_test[2,:]])

array([49.88295231])

In [88]:
lr.score(x_test,y_test)

0.8673945541381713

In [89]:
y_pred=lr.predict(x_test)

In [90]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
print(r2_score(y_test,y_pred))

0.8673945541381713


In [91]:
print(mean_absolute_error(y_test,y_pred))

16.58549697202379


In [92]:
print(mean_squared_error(y_test,y_pred))

1062.1959475611934


In [94]:
import numpy as np
print(np.sqrt(mean_squared_error(y_test,y_pred)))


32.59134774079147
